[package]
name = "day_08"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
util = { path = "../util", version = "0.1.0" }
lazy-regex = "3.1.0"
prime_factorization = "1.0.4"